### ISSUE TITLE
Maven Dependency artifactID needs to be updated on the download website

### ISSUE THREAD

**Issue by mehersam** [BioPAX/Paxtools#16]
The artifact id to import BioPax as a Maven project is actually 'paxtools-core', but the downloads page (http://search.maven.org/#artifactdetails%7Corg.biopax.paxtools%7Cpaxtools%7C4.3.1%7Cpom) indicates it as 'paxtools' and Maven is unable to recognize this.

**Comment by IgorRodchenkov** [comment]
*There's no mistake nor error. *

'paxtools' is the parent project for multi-module maven project that
includes pactools-core, etc., modules/artefacts.
Everything looks and works ok.

Also, that is not a *download* page, technically, and usually you do not
have to manually download maven artefacts. Just add *paxtools-core*
dependency into your *pom.xml* (like it's done, e.g., here
<https://github.com/BioPAX/Paxtools/blob/v4.3.1/json-converter/pom.xml> or
there <https://github.com/PathwayCommons/CyPath2/blob/master/pom.xml>)

Well, if you do not have a Maven project, then you'd include e.g. this
"fat" paxtools JAR
<https://sourceforge.net/projects/biopax/files/paxtools/paxtools-4.3.1-no-jena.jar/download>
into your (Java/Ant, Python, etc.) project.
Also, read the "Availability" section at the end of
https://github.com/BioPAX/Paxtools and the Paxtools publication
<http://dx.plos.org/10.1371/journal.pcbi.1003194>.


See also: http://search.maven.org/#search%7Cga%7C1%7Cpaxtools and
http://repo1.maven.org/maven2/org/biopax/paxtools/ (again, you do not have
to manually download maven artefacts, usually...)


PS:
If you want to use 5.0.0-SNAPSHOT version, add the following to your
pom.xml, to *<repositories>* element:

*<repository>*
*    <id>ossrh-public</id>*
*    <name>OSSRH Maven Repository</name>*
*    <url>https://oss.sonatype.org/content/groups/public
<https://oss.sonatype.org/content/groups/public></url>*
*    <snapshots>*
*    <enabled>true</enabled>*
*    </snapshots>*
*</repository>*
