### ISSUE TITLE
Update to commons-lang 3

### ISSUE THREAD

**Issue by markwoon** [BioPAX/Paxtools#17]
Would it be possible to switch from commons-lang 2 to commons-lang 3?

If so, I'd be willing to submit a PR.

**Comment by IgorRodchenkov** [comment]
We'd try/do this for the next Paxtools release (5.0.0). But is this important, I doubt? A project that uses paxtools as library/dependency could simply exclude commons-lang 2.6 and include 3.x in their POM...

**Comment by markwoon** [comment]
commons-lang 3 is not a drop-in replacement for commons-lang 2.

I'd really appreciate moving updating to 3 because it's caused problems for us before.

I'd be more than happy to do the work if it's something you'll accept.

**Comment by IgorRodchenkov** [comment]
Could you please first explain what kind of problems that caused and why those could not be solved by excluding the transitive dependency or so (or by slightly re-organising your project). Are you using Paxtools' "fat jar" or what? The change may also cause some trouble for other projects, perhaps.
We really wonder and want to hear more. 
In mean time, you are free fork the Paxtools repository and try your ideas; then, create a pull request for others to review and decide to merge or not.

**Comment by markwoon** [comment]
They have classes with the same names, but in different packages.  You can't use paxtools and not have a dependency on commons-lang 2.  The primary reason not to upgrade is if you need to support pre-Java 5 since commons-lang 3 adds support for generics.

We're using commons-lang 3.  We can live with commons-lang 2 if we have to, but since so many things are changing for Paxtools 5 anyway, now would be a good time to upgrade.

We've run into issues where we import a util class from the wrong package (lang2 vs lang3), which leads to downstream packaging issues.  Yes, it's a silly problem, but I just had to deal with such a bug today.  We're using a legacy ant build system and have to manage dependencies by hand.

Like I said, I'm happy to make a PR if you're willing to consider it.  I just don't want to waste my time if it's something that you guys aren't interested in; I've no interest in maintaining my own fork.
