### ISSUE TITLE
SBGN-ML possesses disconnected nodes

### ISSUE THREAD

**Issue by jvwong** [BioPAX/Paxtools#22]
In some cases, the SBGN-ML retrieved from the PC2 web service contains several nodes that are not connected to anything else. 

## Failing case

Pathway: 'Signaling by BMP' -- Reactome

  - [BioPAX record](http://www.pathwaycommons.org/pc2/get?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451)
  - BioPax viewed in ChiBE: chibe_signaling_bmp.png
  - SBGN-ML view: pc_search_signaling_bmp.png

Notes: Viewing the associated BioPAX record in ChiBE reveals ‘Member of’ edge connecting these nodes.    
 
![pc_search_signaling_bmp](https://cloud.githubusercontent.com/assets/4706307/23168848/a39040ca-f817-11e6-84bd-7c2460a52ab8.png)

![chibe_signaling_bmp](https://cloud.githubusercontent.com/assets/4706307/23168856/a815a31a-f817-11e6-9914-0df2cead76dd.png)

**Comment by IgorRodchenkov** [comment]
Attn: @ozgunbabur @istemi-bahceci @cannin  (original developers/contributors of the sbgn-converter module)

**Comment by IgorRodchenkov** [comment]
Looks, the issue is due to using 'memberPhysicalEntity' BioPAX property (e.g., by Reactome), but perhaps not only that.
