### ISSUE TITLE
L3ToSBGNPDConverter.java with predefined layout

### ISSUE THREAD

**Issue by PeterTSmith** [BioPAX/Paxtools#23]
@ozgunbabur 

Hello Ozgun,

I'm working with the L3ToSBGNPDConverter.java trying to find a way to use pre-determined points to position the layouts as an alternative to the Chilay layout that is currently being applied in the createSBGN() method. I would like to ask you a few questions on this and how you might go about doing it.

I would really appreciate your opinion and if you have some time to chat my email is 'peter.t.smith.email@gmail.com'.

Thanks for the consideration,

Peter

**Comment by IgorRodchenkov** [comment]
Great, we've talked already here in UofT. Let's switch to group emails for further discussing this matter.
I am closing this issue, for it's not a technical issue, idea or bug.
