### ISSUE TITLE
Some strings in generated sbgn cause it to be invalid xml

### ISSUE THREAD

**Issue by d2fong** [BioPAX/Paxtools#28]
Pathway: 
http://www.pathwaycommons.org/pc2/get?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-5673000&format=SBGN

Example text:
<label text="dephosphorylated "receiver" RAF/KSR1"/>

The label has "receiver" which closes the value for the text attribute and causes an xml parsing error.

**Comment by d2fong** [comment]
https://github.com/BioPAX/Paxtools/blob/master/sbgn-converter/src/main/java/org/biopax/paxtools/io/sbgn/L3ToSBGNPDConverter.java#L419

This seems to be where a label is generated.

**Comment by IgorRodchenkov** [comment]
Thanks for the catch, I'll look! PC9 beta is up running back again; try it.

**Comment by IgorRodchenkov** [comment]
Dylan, the raw SBGN XML data returned by the query in fact contains:
 <label text="dephosphorylated &quot;receiver&quot; RAF/KSR1"/>
which is correct and should not break an XML parser...

If you process the data returned by PC standard way, properly, rather that unencoding it on the fly somehow (or copy/pasting via a browser), then there is no issue here.

Please confirm.

**Comment by d2fong** [comment]
Okay I will try but you are probably right. I opened it in the browser first which probably decoded it.
