### ISSUE TITLE
Complex members not part of complexes in SBGN output

### ISSUE THREAD

**Issue by ugurdogrusoz** [BioPAX/Paxtools#33]
When PC is queried to return the result in SBGN, it used to be the case that complex members were part of their parent/owner complexes (in SBGNML, member glyphs were simply listed *inside* their owner complex glyphs) but that no longer seems to be the case. From the layout of the returned pathway, it seems like members are properly contained / nested in their parent complexes but that is not the case!
Also see https://github.com/iVis-at-Bilkent/newt/issues/176

**Comment by IgorRodchenkov** [comment]
@ugurdogrusoz , could you please provide a query example (preferably, not too large SBGN-ML result), which e.g. could be used for the jUnit test...

**Comment by IgorRodchenkov** [comment]
I am not convinced that a PC graph query (returning SBGN, which is simply the result of converting and applying layout to the BioPAX sub-network using Paxtools' sbgn-converter) does it wrong: I can see, e.g., complexes look good (see in the target/classes folder) after [the jUnit test](https://github.com/BioPAX/Paxtools/blob/master/sbgn-converter/src/test/java/org/biopax/paxtools/io/sbgn/SBGNConverterTest.java#L192):
```
        <glyph class="complex" id="Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
            <label text="BMP:p-BMPR:Endofin:SMAD1/5/8"/>
            <bbox w="105.0" h="129.00002" x="136.62164" y="177.60197"/>
            <glyph class="macromolecule" id="Protein_ae756c0799a473296ae3d213c27ea5df_Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
                <label text="Type II receptor"/>
                <bbox w="48.0" h="25.0" x="138.62164" y="249.60197"/>
            </glyph>
            <glyph class="macromolecule" id="Protein_33880690357c646d9f33c4462a837720_Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
                <label text="BMP2"/>
                <bbox w="48.0" h="25.0" x="138.62164" y="179.60197"/>
                <glyph class="state variable" id="Protein_33880690357c646d9f33c4462a837720_Complex_2f962a315f3fb9e5f65d1ab529473d1d.info.1" compartmentRef="early_endosome_membrane">
                    <state value="x[283 - 396]"/>
                    <bbox w="35.0" h="10.0" x="145.12164" y="174.60197"/>
                </glyph>
            </glyph>
            <glyph class="macromolecule" id="Protein_cbd95b1234782d618bc2f6cd96d9d907_Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
                <label text="SMAD1/5/8"/>
                <bbox w="48.0" h="25.0" x="138.62164" y="279.602"/>
            </glyph>
            <glyph class="macromolecule" id="Protein_6a3ed4bc09ead0918dd19d7370bd8df5_Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
                <label text="ZFYVE16"/>
                <bbox w="48.0" h="25.0" x="138.62164" y="214.60197"/>
                <glyph class="state variable" id="Protein_6a3ed4bc09ead0918dd19d7370bd8df5_Complex_2f962a315f3fb9e5f65d1ab529473d1d.info.1" compartmentRef="early_endosome_membrane">
                    <state value="x[1 - 1539]"/>
                    <bbox w="35.0" h="10.0" x="145.12164" y="209.60197"/>
                </glyph>
            </glyph>
            <glyph class="macromolecule" id="Protein_d0ba752300c6b80a663f41fc4d04b996_Complex_2f962a315f3fb9e5f65d1ab529473d1d" compartmentRef="early_endosome_membrane">
                <label text="p-4S-BMPRI"/>
                <bbox w="48.0" h="25.0" x="191.62164" y="179.60197"/>
            </glyph>
        </glyph>
```

- and the PC web service uses the same sbgn-converter and does not further modify the SBGN-ML results.

PS:
Refs: iVis-at-Bilkent/newt#176

**Comment by ugurdogrusoz** [comment]
@IgorRodchenkov Let's investigate this further on our side and get back to you

**Comment by ugurdogrusoz** [comment]
Looks like the way compartmentRef's are specified in paxtools is fine. As explained in the related Newt issue (https://github.com/iVis-at-Bilkent/newt/issues/176), since the nesting of objects is more flexible in SBGN but not in visualization library (e.g. Cytoscape.js), we have to ignore complex members' compartmentRefs to resolve our issue.
