### ISSUE TITLE
Does not compile with JDK9-11

### ISSUE THREAD

**Issue by IgorRodchenkov** [BioPAX/Paxtools#43]
Currently, it builds only with JDK8 (and uses Java 1.6 as its source/target compatibility level).

We really need to upgrade/migrate Paxtools project configuration (POM) to make it possible _at least_ to build with JDK9-11, a.s.a.p. And we should also increase the compatibility level to Java 1.8.

PS: I've successfully done this for other projects already, e.g., cpath2 and validator.

**Comment by IgorRodchenkov** [comment]
Better upgrade to use OpenJDK-15

**Comment by adamjohnwright** [comment]
I am working on generating BioPax for Reactome. We upgraded most of our code to run off of Java 11. I am running into runtime errors with our code for generating BioPax files using Java 11 with the latest validator release (4.0.0). Whereas when we use Java 6, it runs without error. Is this ticket correct that 4.0.0 doesn't work with Java 11? And if so, would it be possible to get Igors changes pulled into a release if they fix the issue?

**Comment by IgorRodchenkov** [comment]
Can now build with JDK18
