### ISSUE TITLE
Blank spaces in IDs in SBGN output

### ISSUE THREAD

**Issue by ugurdogrusoz** [BioPAX/Paxtools#44]
Attached is an example of the use of blank spaces in IDs (e.g. "extracellular matrix") when querying PC for SBGN output. This creates problems in libSBGN library (in handling SBGNML files).
[BRCA1_BRCA2_COMMONSTREAM.sbgnml.txt](https://github.com/BioPAX/Paxtools/files/2934608/BRCA1_BRCA2_COMMONSTREAM.sbgnml.txt)

**Comment by IgorRodchenkov** [comment]
@ugurdogrusoz could you please provide the example query URL?

**Comment by ugurdogrusoz** [comment]
http://www.pathwaycommons.org/pc2/graph?source=BRCA1&source=BRCA2&kind=COMMONSTREAM&limit=3&format=SBGN
