### ISSUE TITLE
Problem caused by calling layout while utilizing biopax to sbgn conversion through Python

### ISSUE THREAD

**Issue by metincansiper** [BioPAX/Paxtools#45]
Hi there,

I need to use Paxtools through Python. Therefore, I am running the Java code of Paxtools through Python. I am trying to load a biopax model, making some process on it and finally converting it to sbgn by using sbgn-converter of paxtools. Everything works fine except the biopax to sbgn conversion. 

The problem that happens for the conversion step is that when I call ``writeSBGN()`` of ``L3ToSBGNPDConverter`` the python rocketship icon appears and then the process had not end though I have waited for a while.

I figured out that the problem is gone when I tried to totally eliminate the layout call inside ``createSBGN()`` by commenting out the fallowing code segment:

```
final boolean layout = doLayout && n < this.maxNodes && !arcMap.isEmpty();
try {
	//Must call this, although actual layout might never run;
	//in some real data tests, skipping createLayout method
	//led to malformed SBGN model, unfortunately...
	(new SBGNLayoutManager()).createLayout(sbgn, layout);
} catch (Exception e) {
	throw new RuntimeException("SBGN Layout of " + model.getXmlBase()
			+ ((model.getName()==null) ? "" : model.getName()) + " failed.", e);
}
if(!layout) log.warn(String.format("No layout, for either " +
		"it's disabled: %s, or ~ no. nodes > %s: %s, or - no edges: %s",
		!doLayout, maxNodes, n>maxNodes, arcMap.isEmpty()));
```

The problem persists when I try to prevent the layout by setting the ``doLayout`` parameter as ``false``. BTW I have tried two different libraries to run Java through Python. That libraries are ``jnius`` and ``jpype``. The same thing has happened in both cases.

I have a few questions considering these:

- Do you have any clue about the actual reason why this would be happening? I mean what may be happening differently during the layout? I may try to find a solution based on that reason.
- Would you consider to make the the layout totally optional (I mean even not calling by setting the ``doLayout`` parameter as ``false``)
- How and why skipping layout causes the malformed sbgn model when the layout is skipped?
- (If needed) Am I allowed to modify the Paxtools source code in my own fork to create my own jar?

**Comment by metincansiper** [comment]
BTW looks like I am able to make it work by using paxtools 5.0.1 and disabling the layout (looks like in that version layout can totally be ignored optionally) but it would still be better if I would make it work with the newer versions of paxtools so that I could get the updates as needed. 

Also, I wonder even though paxtools 5.0.1 allows me to ignore the layout totally if doing so would cause the problems mentioned in the newer version of paxtools.

**Comment by IgorRodchenkov** [comment]
Metin, you're the author of the Paxtools' SBGN layout. We stopped using
Paxtools SBGN layout feature in PC a couple of releases ago due to various
problems,
and there is no issues so far. PC uses Paxtools 5.2.1 dependencies (Maven
project).
E.g.,
https://www.pathwaycommons.org/pc2/get?uri=http://identifiers.org/reactome/R-HSA-201451&format=sbgn
*Of course, you can fork Paxtools, fix, open a PR*. You were a member of
Pathway Commons team as I remember,
so what's the problem? I also suspect that the BioPAX model you were making
with Python had some issues, inconsistencies.
Try to export it to a OWL file and validate with the BioPAX Validator first.

I am not working in PC anymore.
