### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by jmaggiore** [BioPAX/Paxtools#48]
Hi there, what is the most efficient way if I have a list of around ~50 genes to output a data frame in r that contains only the controls-state-of interaction type but for all the ~50 genes? When I query using this code it just takes such a long time and is outputting way more than I need.

t1 <- graphPc(source = 50_genes, kind = "NEIGHBORHOOD", format = "SIF", verbose = TRUE, limit = 1)

**Comment by IgorRodchenkov** [comment]
Github project issues are not for how-to or research questions.
